Taylor(тесты проходит но с синусом есть вопросы)
HappyLumpy/PY111 pull request #10
Opened 2021-06-18 19:22 UTC by HappyLumpy

2021-06-22 10:16 UTC, EnotYoyo requested changes
Я говорил, что решать эти задания нужно наиболее эффективным способом. Вызывать факториал числа i, когда на предыдущем шаге посчитан факториал i - 1 крайне неэффективно. 

Аналогично для возведения в степень. 

Нужно использовать вычисления, которые были сделаны на предыдущем шаге итерации.

2021-06-23 17:51 UTC, HappyLumpy commented
не могу понять мы же в sin(x) считаем факториал с шагом отличным от 1, и разница между прошлым значением и следующим в факториале вроде без зависимости

2021-06-25 19:21 UTC, EnotYoyo commented
> не могу понять мы же в sin(x) считаем факториал с шагом отличным от 1, и разница между прошлым значением и следующим в факториале вроде без зависимости

Но Вы можете отдельно считать числитель и знаменатель. На каждом шаге вычислять новые значения, используя значения с предыдущего шага.

2021-06-25 19:21 UTC, EnotYoyo commented
> > не могу понять мы же в sin(x) считаем факториал с шагом отличным от 1, и разница между прошлым значением и следующим в факториале вроде без зависимости
> 
> Но Вы можете отдельно считать числитель и знаменатель. На каждом шаге вычислять новые значения, используя значения с предыдущего шага.

Попробуйте вначале с экспонентой. Там чуть проще.

2021-06-28 21:18 UTC, EnotYoyo approved these changes
Принято, но комментарии лучше поправить

2021-06-28 21:18 UTC, EnotYoyo commented on Tasks/b2_Taylor.py
> +        e = e + (x ** i) / f
Числитель тоже можно вычислять эффективно, не возводя каждый раз в степень

2021-06-28 21:18 UTC, EnotYoyo commented on Tasks/b2_Taylor.py
> +        if f == 0:
Имеет смысл просто цикл с 1 начать. Для этого нужно немного поменять начальное значение e

2021-06-28 21:18 UTC, EnotYoyo commented on Tasks/b2_Taylor.py
> +        if i != 0:
имеет смысл начать цикл с 1

2021-06-30 16:45 UTC, merged