Horse
HappyLumpy/PY111 pull request #12
Opened 2021-06-28 18:13 UTC by HappyLumpy

2021-06-28 21:19 UTC, EnotYoyo requested changes
Тесты не проходят

2021-07-05 19:37 UTC, EnotYoyo commented on Tasks/d1_horse.py
> +                    field[y+1][x+2] = 2 * field[y][x] + field[y+1][x+2]
ну тут явно напрашивается использование `+=`.  Это лучше читается и явно показывает намерение.

2021-07-05 19:38 UTC, EnotYoyo approved these changes
Лошадь принята.

2021-07-05 20:00 UTC, HappyLumpy commented on Tasks/d1_horse.py
> +                    field[y+1][x+2] = 2 * field[y][x] + field[y+1][x+2]
немного не понимаю что можно заменить на += попробовал несколько вариантов и тесты сразу не проходит

2021-07-05 22:02 UTC, EnotYoyo commented on Tasks/d1_horse.py
> +                    field[y+1][x+2] = 2 * field[y][x] + field[y+1][x+2]
`field[y+1][x+2] = 2 * field[y][x] + field[y+1][x+2]` на `field[y+1][x+2] += 2 * field[y][x]`

2021-07-06 18:49 UTC, merged