check_brackets(через регулярку)
HappyLumpy/PY111 pull request #4
Opened 2021-05-23 16:58 UTC by HappyLumpy

2021-05-23 17:16 UTC, EnotYoyo requested changes
Не сработает для вариант "())(()". Регулярки тут не нужны, достаточно счетчика, но его нужно доработать.

2021-05-23 18:17 UTC, HappyLumpy commented
В последнем варианте:
1. Убрал лишний import 
2. Добавил прерывание цикла в случае неправильно открытой скобки

2021-05-23 19:13 UTC, EnotYoyo approved these changes
Принято.

2021-05-23 19:13 UTC, EnotYoyo commented on Tasks/a3_check_brackets.py
> +    if count_brackets == 0:
В таких случаях можно сократить код: 
```python 
return count_brackets == 0
```

2021-05-23 19:13 UTC, EnotYoyo commented on Tasks/a3_check_brackets.py
> +        if brackets == '(' and count_brackets != -1:
Вторая проверка (`count_brackets != -1`) тут лишняя.

2021-05-24 17:17 UTC, merged

2021-05-24 17:20 UTC, HappyLumpy commented
на время в тестах смотреть не имеет смысла (в целях улучшения быстродействия программы)?