Бинарный поиск через рекурсию(не рабочий)
HappyLumpy/PY111 pull request #9
Opened 2021-06-14 19:44 UTC by HappyLumpy

Не могу понять как реализовать данный поиск, если подтолкнёте в нужную сторону буду благодарен.

2021-06-18 17:31 UTC, HappyLumpy commented
почему-то даже первую проверку не делает. 
если значение первого будет больше чем последнего то он должен выдавать None, но почему-то не делает этого

2021-06-18 17:38 UTC, HappyLumpy commented
Остался вопрос с значением Last по умолчанию

2021-06-22 10:14 UTC, EnotYoyo requested changes

2021-06-22 10:14 UTC, EnotYoyo commented on Tasks/c2_recursive_binary_search.py
> +            return midval
А почему возвращается индекс?

2021-06-22 10:14 UTC, EnotYoyo commented on Tasks/c2_recursive_binary_search.py
> +def binary_search(elem: int, arr: Sequence, fist=0, last=1) -> Optional[int]:
На начальном запуске у нас получается, что first = 0, last = 1.. Хотя очевидно, что last должен быть равен len(arr) - 1.

2021-06-23 16:16 UTC, HappyLumpy commented on Tasks/c2_recursive_binary_search.py
> +            return midval
так вроде по заданию нужно индекс вернуть ?
" :return: Index of element if it's presented in the arr, None otherwise"

2021-06-23 16:20 UTC, HappyLumpy commented on Tasks/c2_recursive_binary_search.py
> +def binary_search(elem: int, arr: Sequence, fist=0, last=1) -> Optional[int]:
а как возможно len(arr)-1 в параметры функции ?
просто сколько бы я не искал не смог найти как это сделать.

2021-06-25 19:18 UTC, EnotYoyo commented on Tasks/c2_recursive_binary_search.py
> +            return midval
Да, прошу прощения. Странное что-то написал.

2021-06-25 19:19 UTC, EnotYoyo commented on Tasks/c2_recursive_binary_search.py
> +def binary_search(elem: int, arr: Sequence, fist=0, last=1) -> Optional[int]:
Нельзя. Но можно сделать через None: 
```python
def binary_search(elem: int, arr: Sequence, fist=0, last=None) -> Optional[int]:
  if last is None:
        last = ...
```

2021-06-28 21:13 UTC, EnotYoyo approved these changes
Принято

2021-06-30 16:45 UTC, merged